### ISSUE TITLE
Git SCM migration

### ISSUE THREAD

**Issue by halverneus** [randycoulman/jujube#14]
Goal is to add 'credentials-id', remove branch limitation and remove the gitweb browser option. Add option for overriding repository slug (in this case from "myProject" to "my-project").

convert output from:

```yaml
scm:
    - git:
        url: git@my-server:myProject.git
        branches:
        - master
        browser: gitweb
        browser-url: http://se-world/gitweb/?p=avcInstallationCD.git
        wipe-workspace: false
```

to:

```yaml
scm:
    - git:
        url: git@newrepo.com:project/my-project.git
        credentials-id: a471c329-f3a9-22b1-a893-0123b3c462a1
        branches:
        - master
        wipe-workspace: false
``
