### ISSUE TITLE
Support Gitlab trigger

### ISSUE THREAD

**Issue by halverneus** [randycoulman/jujube#15]
Convert triggers from pollscm to GitLab-based webhooks:

Original:

```yaml
triggers:
    - pollscm:
        cron: "@daily"
```

New:

```yaml
triggers:
    - gitlab:
        trigger-push: true
        trigger-merge-request: true
        trigger-accepted-merge-request: true
        trigger-closed-merge-request: true
        trigger-open-merge-request-push: source
        allow-all-branches: true
        trigger-note: false
```
