### ISSUE TITLE
Add GitLab notifier

### ISSUE THREAD

**Issue by halverneus** [randycoulman/jujube#16]
Add following publisher:

```yaml
publishers:
    - gitlab-notifier:
        name: jenkins
        mark-unstable-as-success: false
```
